Repository kyma-project/interactive-tutorials, pull requests merged in 2023-06, with the labels that each got.

#10 Use internal docker registry in serverless tutorial
  serverless/index.json
  serverless/init.sh
  serverless/registry.md
  serverless/serverless.md
Labels: size/M, lgtm

#12 Update language and formatting in the Modular Kyma tutorial
  modular-kyma/channel1.md
  modular-kyma/channel2.md
  modular-kyma/channel_intro.md
  modular-kyma/intro.md
  modular-kyma/modules.md
  modular-kyma/setup-access.md
Labels: size/M, lgtm

#13 Rate limit
  rate-limit/assets/httpbin.yaml
  rate-limit/assets/istio-profile.yaml
  rate-limit/assets/rate-limit-config.yaml
  rate-limit/assets/rate-limit-filters.yaml
  rate-limit/assets/rate-limit-service.yaml
  rate-limit/index.json
  rate-limit/init.sh
  rate-limit/intro.md
  rate-limit/rate-limit.md
Labels: size/XL

#14 Btp-manager update
  btp-services/assets/btp-manager.yaml
  btp-services/btp-manager.md
  serverless/serverless.md
Labels: size/L

#15 Update btp-manager.md
  btp-services/btp-manager.md
Labels: lgtm, size/S
