Repository kyma-project/interactive-tutorials, pull requests merged in 2023-03, with the labels that each got.

#1 Switch default installation to latest release
  cluster-ip/cluster-ip.md
Labels: size/XS

#3 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS

#4 replace Keda module template with official one deployed by kyma cli
  modular-kyma/assets/modules.yaml
  modular-kyma/modules.md
Labels: size/M, lgtm

#5 Add Manage Channel tutorial
  modular-kyma/assets/cluster-ip-module-template-beta.yaml
  modular-kyma/assets/cluster-ip-module-template-fast-upgraded.yaml
  modular-kyma/assets/cluster-ip-module-template-fast.yaml
  modular-kyma/assets/cluster-ip-module-template.yaml
  modular-kyma/assets/modules.yaml
  modular-kyma/channel1.md
  modular-kyma/channel2.md
  modular-kyma/channel_intro.md
  modular-kyma/index.json
  modular-kyma/kyma-init.sh
  modular-kyma/modules.md
Labels: size/L, lgtm

#6 Follow up to the serverless dependencies fix
  serverless/init.sh
  serverless/serverless.md
Labels: size/XS, lgtm
